# Generated by Django 2.2.4 on 2022-06-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastt_name',
            new_name='last_name',
        ),
    ]
